spring.application.name=full_Project

spring.autoconfigure.exclude=\
  org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration,\
  org.springframework.boot.security.autoconfigure.SecurityFilterChainAutoConfiguration,\
  org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration,\
  org.springframework.boot.security.autoconfigure.web.servlet.ServletWebSecurityAutoConfiguration

# DATASOURCE

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/full_Project
spring.datasource.username=root
spring.datasource.password=

# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=false


jwt.secret=mysupercomplexsecret

server.error.path=/user/error
server.error.whitelabel.enabled=false

logging.level.org.springframework.security=DEBUG
logging.level.io.Rafa_lol.full_Project=DEBUG